entity.1599=minecraft:entity_shadow
entity.1600=minecraft:name_tag

entity.1601=player

entity.1602=minecraft:lightning_bolt weather2:lightning_bolt

## misc stuff

entity.1603=blaze minecraft:entity_flame
# TODO: Why is entity flame in both `ENTITY_SPECTRAL_ARROW` and `ENTITY_BLAZE` ???

entity.1604=ender_dragon wither

entity.1605=end_crystal

entity.1606=glow_squid

entity.1607=item_frame item_display

entity.1608=magma_cube

entity.1609=tnt firework_rocket

entity.1610=small_fireball

entity.1611=spectral_arrow bigglobe:torch_arrow entity_flame
# TODO: Why is entity flame in both `ENTITY_SPECTRAL_ARROW` and `ENTITY_BLAZE` ???

entity.1612=boat chest_boat oak_boat oak_chest_boat birch_boat birch_chest_boat dark_oak_boat dark_oak_chest_boat spruce_boat spruce_chest_boat acacia_boat acacia_chest_boat pale_oak_boat pale_oak_chest_boat jungle_boat jungle_chest_boat mangrove_boat mangrove_chest_boat cherry_boat cherry_chest_boat \
  smallships:drakkar smallships:galley

entity.1613=smallships:cog smallships:brigg

entity.1614=current_player
################################################
###### SUB-SURFACE SCATTERING
################################################

## medium sss (same as strong sss for blocks)
entity.1801=giant ghast happy_ghast elder_guardian sniffer magma_cube \
 naturalist:butterfly naturalist:firefly naturalist:caterpillar naturalist:dragonfly

## weak sss (same as weak sss for blocks)
entity.1802=warden furnace_minecart sheep frog chicken iron_golem snow_golem polar_bear zombie_horse armor_stand arrow squid bat cat cod cow donkey fox horse mooshroom mule ocelot parrot pig piglin pufferfish rabbit salmon strider tropical_fish turtle villager wandering_trader bee cave_spider dolphin enderman llama panda spider wolf zombified_piglin creeper drowned endermite evoker guardian hoglin husk phantom piglin_brute pillager ravager silverfish vex vindicator witch zoglin zombie zombie_villager trader_llama nautilus zombie_nautilus camel_husk creaking bogged axolotl armadillo goat tadpole copper_golem \
 naturalist:bear naturalist:snail naturalist:snake naturalist:coral_snake naturalist:rattlesnake naturalist:bluejay naturalist:cardinal naturalist:canary naturalist:robin naturalist:finch naturalist:sparrow naturalist:rhino naturalist:elephant naturalist:lion naturalist:zebra naturalist:giraffe naturalist:hippo naturalist:vulture naturalist:boar naturalist:catfish naturalist:alligator naturalist:bass naturalist:tortoise naturalist:duck
#removed: player blaze magma_cube

## no sss
entity.1803=skeleton wither_skeleton skeleton_horse stray parched

################################################
###### REFLECTIVE TRANSLUCENTS
################################################

entity.1804=slime